apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::080120290987:role/eksctl-eksctl-demo-nodegroup-ng-4-NodeInstanceRole-B462NRP870V2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::080120290987:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-12T20:11:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1350"
  uid: 5a3d80eb-88e6-4de1-b282-a58bc1ed5c99
